server:
  port: 8000
spring:
  application:
  name: RentAcar
  datasource:
    url: jdbc:postgresql://localhost:5432/rentacar?serverTimeZone=ADT
    username: postgres
    password: 123456
jpa:
    hibernate:
      ddl-auto: update
    show-sql: true